image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable

build:
  project: ExampleProject.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\MyUnitTests\bin\Debug\MyUnitTests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\MyProject_coverage.xml"
- ps: Invoke-WebRequest -Uri https://github.com/codacy/csharp-codacy-coverage/releases/download/$env:CODACY_COVERAGE_VERSION/Codacy.CSharpCoverage_win-x64.exe -OutFile C:\temp\Codacy.CSharpCoverage_win-x64.exe
- ps: C:\temp\Codacy.CSharpCoverage_win-x64.exe -c $env:APPVEYOR_REPO_COMMIT -t $env:CODACY_PROJECT_TOKEN -r MyProject_coverage.xml -e opencover

artifacts:
  - path: MyProject_coverage.xml
    name: MyProject_coverage
