image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable

build:
  project: ExampleProject.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\MyUnitTests\bin\Debug\MyUnitTests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\MyProject_coverage.xml"
- ps: Invoke-WebRequest -Uri https://dl.dropboxusercontent.com/s/arbklbtybu5pfm3/csharp-codacy-coverage_win-x64.zip?dl=0 -OutFile csharp-codacy-coverage_win-x64.zip
- ps: Expand-Archive csharp-codacy-coverage_win-x64.zip -DestinationPath C:\temp\Codacy.CSharpCoverage\
- ps: C:\temp\Codacy.CSharpCoverage\Codacy.CSharpCoverage.exe -c $env:APPVEYOR_REPO_COMMIT -t $env:CODACY_PROJECT_TOKEN -r MyProject_coverage.xml -e opencover

artifacts:
  - path: MyProject_coverage.xml
    name: MyProject_coverage